{% set name = "ryvencore" %}
{% set version = "0.3.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ryvencore-{{ version }}.tar.gz
  sha256: f2099923ceb28bc5effbbd0435623d700b259e460233638558a4cdcb41026d8b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ryvencore
    - ryvencore.dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leon-thomm/ryvencore
  summary: Python backend for node editor-like graph-based processing
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
