{% set name = "ryvencore" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ryvencore-{{ version }}.tar.gz
  sha256: fdc09fcbedc42e62743e3a4255f0325ede47e44ab4ffe17168956ff03bc28e42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - packaging

test:
  imports:
    - ryvencore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leon-thomm/ryvencore
  summary: Python backend for node editor-like graph-based processing
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
